package keycodes

/*
 * Short names for ease of definition of keymap
 */
const (
	LCTL = LCTRL
	RCTL = RCTRL
	LSFT = LSHIFT
	RSFT = RSHIFT
	ESC  = ESCAPE
	BSPC = BSPACE
	ENT  = ENTER
	DEL  = DELETE
	INS  = INSERT
	CAPS = CAPSLOCK
	CLCK = CAPSLOCK
	RGHT = RIGHT
	PGDN = PGDOWN
	PSCR = PSCREEN
	SLCK = SCROLLLOCK
	PAUS = PAUSE
	BRK  = PAUSE
	NLCK = NUMLOCK
	SPC  = SPACE
	MINS = MINUS
	EQL  = EQUAL
	GRV  = GRAVE
	RBRC = RBRACKET
	LBRC = LBRACKET
	COMM = COMMA
	BSLS = BSLASH
	SLSH = SLASH
	SCLN = SCOLON
	QUOT = QUOTE
	APP  = APPLICATION
	NUHS = NONUS_HASH
	NUBS = NONUS_BSLASH
	LCAP = LOCKING_CAPS
	LNUM = LOCKING_NUM
	LSCR = LOCKING_SCROLL
	ERAS = ALT_ERASE
	CLR  = CLEAR

	/* Japanese specific */
	ZKHK = GRAVE
	RO   = INT1
	KANA = INT2
	JYEN = INT3
	JPY  = INT3
	HENK = INT4
	MHEN = INT5

	/* Korean specific */
	HAEN = LANG1
	HANJ = LANG2

	/* Keypad */
	P1   = KP_1
	P2   = KP_2
	P3   = KP_3
	P4   = KP_4
	P5   = KP_5
	P6   = KP_6
	P7   = KP_7
	P8   = KP_8
	P9   = KP_9
	P0   = KP_0
	PDOT = KP_DOT
	PCMM = KP_COMMA
	PSLS = KP_SLASH
	PAST = KP_ASTERISK
	PMNS = KP_MINUS
	PPLS = KP_PLUS
	PEQL = KP_EQUAL
	PENT = KP_ENTER

	/* Unix function key */
	EXEC = EXECUTE
	SLCT = SELECT
	AGIN = AGAIN
	PSTE = PASTE

	/* Mousekey */
	MS_U = MS_UP
	MS_D = MS_DOWN
	MS_L = MS_LEFT
	MS_R = MS_RIGHT
	BTN1 = MS_BTN1
	BTN2 = MS_BTN2
	BTN3 = MS_BTN3
	BTN4 = MS_BTN4
	BTN5 = MS_BTN5
	WH_U = MS_WH_UP
	WH_D = MS_WH_DOWN
	WH_L = MS_WH_LEFT
	WH_R = MS_WH_RIGHT
	ACL0 = MS_ACCEL0
	ACL1 = MS_ACCEL1
	ACL2 = MS_ACCEL2

	/* Sytem Control */
	PWR  = SYSTEM_POWER
	SLEP = SYSTEM_SLEEP
	WAKE = SYSTEM_WAKE

	/* Consumer Page */
	MUTE = AUDIO_MUTE
	VOLU = AUDIO_VOL_UP
	VOLD = AUDIO_VOL_DOWN
	MNXT = MEDIA_NEXT_TRACK
	MPRV = MEDIA_PREV_TRACK
	MFFD = MEDIA_FAST_FORWARD
	MRWD = MEDIA_REWIND
	MSTP = MEDIA_STOP
	MPLY = MEDIA_PLAY_PAUSE
	EJCT = MEDIA_EJECT
	MSEL = MEDIA_SELECT
	CALC = CALCULATOR
	MYCM = MY_COMPUTER
	WSCH = WWW_SEARCH
	WHOM = WWW_HOME
	WBAK = WWW_BACK
	WFWD = WWW_FORWARD
	WSTP = WWW_STOP
	WREF = WWW_REFRESH
	WFAV = WWW_FAVORITES

	/* Jump to bootloader */
	BTLD = BOOTLOADER
	PROG = BOOTLOADER

	/* Transparent */
	TRANSPARENT = 1
	TRNS        = TRANSPARENT
)
