// Code generated by "stringer -type=ViaKeyboardValueID -trimprefix=ViaKbd"; DO NOT EDIT.

package vial

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ViaKbdUptime-1]
	_ = x[ViaKbdLayoutOptions-2]
	_ = x[ViaKbdSwitchMatrixState-3]
	_ = x[ViaKbdFirmwareVersion-4]
	_ = x[ViaKbdDeviceIndication-5]
}

const _ViaKeyboardValueID_name = "UptimeLayoutOptionsSwitchMatrixStateFirmwareVersionDeviceIndication"

var _ViaKeyboardValueID_index = [...]uint8{0, 6, 19, 36, 51, 67}

func (i ViaKeyboardValueID) String() string {
	i -= 1
	if i >= ViaKeyboardValueID(len(_ViaKeyboardValueID_index)-1) {
		return "ViaKeyboardValueID(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ViaKeyboardValueID_name[_ViaKeyboardValueID_index[i]:_ViaKeyboardValueID_index[i+1]]
}
