// Code generated by "stringer -type=VialRGBGetCommand"; DO NOT EDIT.

package vial

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VialRGBCommandGetInfo-64]
	_ = x[VialRGBCommandGetMode-65]
	_ = x[VialRGBCommandGetSupported-66]
	_ = x[VialRGBCommandGetNumberLEDs-67]
	_ = x[VialRGBCommandGetLEDInfo-68]
}

const _VialRGBGetCommand_name = "VialRGBCommandGetInfoVialRGBCommandGetModeVialRGBCommandGetSupportedVialRGBCommandGetNumberLEDsVialRGBCommandGetLEDInfo"

var _VialRGBGetCommand_index = [...]uint8{0, 21, 42, 68, 95, 119}

func (i VialRGBGetCommand) String() string {
	i -= 64
	if i >= VialRGBGetCommand(len(_VialRGBGetCommand_index)-1) {
		return "VialRGBGetCommand(" + strconv.FormatInt(int64(i+64), 10) + ")"
	}
	return _VialRGBGetCommand_name[_VialRGBGetCommand_index[i]:_VialRGBGetCommand_index[i+1]]
}
