// Code generated by "stringer -type=VialRGBSetCommand"; DO NOT EDIT.

package vial

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VialRGBCommandSetMode-65]
	_ = x[VialRGBCommandDirectFastset-66]
}

const _VialRGBSetCommand_name = "VialRGBCommandSetModeVialRGBCommandDirectFastset"

var _VialRGBSetCommand_index = [...]uint8{0, 21, 48}

func (i VialRGBSetCommand) String() string {
	i -= 65
	if i >= VialRGBSetCommand(len(_VialRGBSetCommand_index)-1) {
		return "VialRGBSetCommand(" + strconv.FormatInt(int64(i+65), 10) + ")"
	}
	return _VialRGBSetCommand_name[_VialRGBSetCommand_index[i]:_VialRGBSetCommand_index[i+1]]
}
