// Code generated by "stringer -type=ViaQmkRGBLightValue"; DO NOT EDIT.

package vial

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ViaQmkRGBLightBrightness-128]
	_ = x[ViaQmkRGBLightEffect-129]
	_ = x[ViaQmkRGBLightEffectSpeed-130]
	_ = x[ViaQmkRGBLightColor-131]
}

const _ViaQmkRGBLightValue_name = "ViaQmkRGBLightBrightnessViaQmkRGBLightEffectViaQmkRGBLightEffectSpeedViaQmkRGBLightColor"

var _ViaQmkRGBLightValue_index = [...]uint8{0, 24, 44, 69, 88}

func (i ViaQmkRGBLightValue) String() string {
	i -= 128
	if i >= ViaQmkRGBLightValue(len(_ViaQmkRGBLightValue_index)-1) {
		return "ViaQmkRGBLightValue(" + strconv.FormatInt(int64(i+128), 10) + ")"
	}
	return _ViaQmkRGBLightValue_name[_ViaQmkRGBLightValue_index[i]:_ViaQmkRGBLightValue_index[i+1]]
}
