// Code generated by "stringer -type=ViaQmkRGBMatrixValue"; DO NOT EDIT.

package vial

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ViaQmkRGBMatrixBrightness-1]
	_ = x[ViaQmkRGBMatrixEffect-2]
	_ = x[ViaQmkRGBMatrixEffectSpeed-3]
	_ = x[ViaQmkRGBMatrixColor-4]
}

const _ViaQmkRGBMatrixValue_name = "ViaQmkRGBMatrixBrightnessViaQmkRGBMatrixEffectViaQmkRGBMatrixEffectSpeedViaQmkRGBMatrixColor"

var _ViaQmkRGBMatrixValue_index = [...]uint8{0, 25, 46, 72, 92}

func (i ViaQmkRGBMatrixValue) String() string {
	i -= 1
	if i >= ViaQmkRGBMatrixValue(len(_ViaQmkRGBMatrixValue_index)-1) {
		return "ViaQmkRGBMatrixValue(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ViaQmkRGBMatrixValue_name[_ViaQmkRGBMatrixValue_index[i]:_ViaQmkRGBMatrixValue_index[i+1]]
}
